dependencies:
- name: btcd-kube
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.51
- name: lnd-kube
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.19
- name: bitcoind-kube
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
